# Site identity
title: dotlineform
url: "https://www.dotlineform.com"
baseurl: ""  # custom domain: leave empty
media_base: ""
media_prefix: /assets/works/img
files_prefix: /assets/works/files
# when using a separate media server, uncomment and set the following:
# media_base: https://media.dotlineform.com
# media_prefix: /works/img
# files_prefix: /assets/works/files

exclude:
  - scripts

collections:
  research:
    output: true
    permalink: /research/:name/  # clean note URLs
  moments:
    output: true
    permalink: /moments/:name/
  works:
    output: true
    permalink: /works/:name/
  themes:
    output: true
    permalink: /themes/:name/

defaults:
  - scope:
      path: ""
      type: research
    values:
      layout: research
  - scope:
      path: ""
      type: moments
    values:
      layout: moment
  - scope:
      path: ""
      type: works
    values:
      layout: work
  - scope:
      path: ""
      type: themes
    values:
      layout: theme    
  # Apply default layout automatically to other pages
  - scope:
      path: ""
    values:
      layout: default